services:
  go-server:
    image: golang:1.20
    working_dir: /app
    volumes:
      - .:/app
    command: go run main.go
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - api-key=c4game